# Generated by Django 5.1.1 on 2024-10-11 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AddField(
            model_name='mailing',
            name='title',
            field=models.CharField(default='Без названия', max_length=100, verbose_name='Название рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='clients',
            field=models.ManyToManyField(to='mail_messages.client', verbose_name='Клиенты'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mail_messages.message', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='periodicity',
            field=models.CharField(choices=[('daily', 'Раз в день'), ('weekly', 'Раз в неделю'), ('monthly', 'Раз в месяц')], max_length=10, verbose_name='Периодичность рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start_datetime',
            field=models.DateTimeField(verbose_name='Дата и время первой рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('started', 'Запущена'), ('completed', 'Завершена')], default='created', max_length=10, verbose_name='Статус рассылки'),
        ),
    ]
