# Generated by Django 5.1.1 on 2024-10-14 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_messages', '0004_alter_client_owner_alter_mailing_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_view_mailing', 'Can view mailing'), ('can_disable_mailing', 'Can disable mailing')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
