# Generated by Django 5.1.1 on 2024-10-14 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_messages', '0005_alter_mailing_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_disable_mailing', 'Can disable mailing')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
