# Generated by Django 5.1.1 on 2024-10-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_messages', '0006_alter_mailing_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активность рассылки'),
        ),
    ]
